# Higher taxa of a NCBI taxonomy ID (ordered by taxonomic levels; only for Virtuoso)
#param 511145
SELECT ?taxon ?name ?rank
{
    tax:$1 up:replacedBy* ?taxid . # taxid can be replaced with a new one.
    ?taxid rdfs:subClassOf ?taxon option(transitive, t_direction 1, t_min 0, t_step("step_no") as ?level) . # only for Virtuoso
    ?taxon up:scientificName ?name .
    OPTIONAL {
        ?taxon up:rank ?rank .
    }
    # FILTER (?taxon != tax:131567) # Omit the top level "cellular organisms"
}
ORDER BY DESC(?level)
